l
name: Run on Pull Request Workflow Completion

on:
  workflow_run:
    workflows: ["Deploy to trigger workflows"]
    types:
      - completed

jobs:
  run_after_completion:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && !github.event.workflow_run.head_repository.fork }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
        
      - name: Post-workflow step
        run: echo "This runs after the pull request workflow completes successfully."

      - name: Tag Code and push
        env:
          XTS_CANDIDATE_TAG: "xts-candidate"
        run: |
          # Configure Git user
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          
          # Create or update the XTS_CANDIDATE_TAG and push it
          git tag --force ${XTS_CANDIDATE_TAG} --message "Tagging commit for XTS promotion"
          git push --set-upstream origin --tags

      - name: Print github.event.workflow_run properties
        run: |
          echo "Printing github.event.workflow_run properties:"
          echo "${{ toJson(github.event.workflow_run) }}"
